### ISSUE TITLE
How to set an environment variable in the previous request and then pass it into the following request?

### ISSUE THREAD

**Issue by sophiecdd** [postmanlabs/newman#1029]
1. Newman Version (can be found via `newman -v`): 3.6.0
 2. OS details (type, version, and architecture): windows7
 3. Are you using Newman as a library, or via the CLI? via CLI
 3. Did you encounter this recently, or has this bug always been there: just started to use newman recently
 4. Expected behaviour: I am expecting the environment variable get set during request1 then from request2, I can pass in the value into the header
 5. Command / script used to run Newman:
newman run collection.json -e env.json
 6. Sample collection, and auxilliary files (minus the sensitive details):
I am running the following collection from command line and having an env json exported with base_url and cookie, the cookie value is set during the first request run. Can I do the following to get the environment variable set and pass along?
```json
{
	"variables": [],
	"info": {
		"name": "Sophie",
		"_postman_id": "1eb379e2-2e4e-6c43-c72e-1127cd3e1f0b",
		"description": "Sophie's Test",
		"schema": "https://schema.getpostman.com/json/collection/v2.0.0/collection.json"
	},
	"item": [
		{
			"name": "get",
			"description": "",
			"item": [
				{
					"name": "login",
					"event": [
						{
							"listen": "test",
							"script": {
								"type": "text/javascript",
								"exec": [
									"tests[\"Status code is 200\"] = responseCode.code === 200;",
									"postman.setEnvironmentVariable(\"cookie\", \"loginSession=\"+postman.getResponseCookie(\"loginSession\").value);",
									""
								]
							}
						}
					],
					"request": {
						"url": "http://{{base_url}}/sophie_ui/",
						"method": "GET",
						"header": [
							{
								"key": "Accept",
								"value": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
								"description": ""
							}
						],
						"body": {},
						"description": ""
					},
					"response": []
				},
				{
					"name": "login with username/pwd",
					"event": [
						{
							"listen": "test",
							"script": {
								"type": "text/javascript",
								"exec": [
									"tests[\"Status code is 200\"] = responseCode.code === 200;"
								]
							}
						}
					],
					"request": {
						"url": "http://{{base_url}}/login/security_check",
						"method": "POST",
						"header": [
							{
								"key": "Cookie",
								"value": "{{**cookie**}}",
								"description": ""
							}
						],
						"body": {
							"mode": "raw",
							"raw": "j_username=&j_password="
						},
						"description": ""
					},
					"response": []
				}
			]
		}
	]
}
```

 7. Screenshots (if applicable):

**Comment by shamasis** [comment]
Perfect. You can variables use like that. Is there any issue coming up when you use it like that?

**Comment by sophiecdd** [comment]
It didn't work for me through command line, from UI works fine. But running from command line gave me back errors, is there a way to printout the actual response body in the console output?

**Comment by sophiecdd** [comment]
And also, same question as I asked on the closed thread earlier yesterday. Since the value of that environmental parameter is change dynamically, is it possible that the following test case is not getting the updated value?

**Comment by kunagpal** [comment]
@sophiecdd Could you share the command used (if different from the command provided in the opening comment), the error encountered? Also, you'd have to add `--export-environment <the-name-of-your-env-file>` to your `newman run ...` command so that the original environment file get's replaced with the updated one.

**Comment by sophiecdd** [comment]
Here is what I am doing in my test:
1. get request to load a login page (get a cookie which will be passed into the rest of the request in the header)
2. post request to pass the authentication with username/password
3. get request(need the cookie from step #1), the test is failing here for me

I am using the following command to run it through command line:
newman run collection.json -e env.json

if I add the --export-environment <the-name-of-your-env-file> to the run command, the export will only run at the end of the run right? Does that mean #3 will run using the old value from env file?

**Comment by sophiecdd** [comment]
BTW, the reason why I have to do the first two step is, we have to by pass a firewall and a cross product authentication. And I know this is not good from testing point of view, but I have no control of these :)

**Comment by shamasis** [comment]
Good that you mentioned Cookie. You cannot set cookie programmatically from postman or Newman, everything else retains whatever you do with variables through all requests in a run. 

So, when you get cookie from 1, you can set its value as anything else in 3, but not as cookie. 

https://www.getpostman.com/docs/chaining_requests

**Comment by sophiecdd** [comment]
@shamasis Thanks for your reply, but something here I don't understand, if like what you said that postman and newman doesn't support setting cookie programmatically, why it is working for me from postman client? Also with the Interceptor ON, I do see cookie get set though.

**Comment by shamasis** [comment]
That's odd. @numaanashraf @czardoz can you help out here? Maybe I missed something.

**Comment by sophiecdd** [comment]
I found this post: https://www.linkedin.com/pulse/how-read-cookie-value-postman-request-chaining-ishan-girdhar-oscp

**Comment by sophiecdd** [comment]
Hi, it is me made a mistake, postman client remembers the cookie from the web login, so it worked for me from there. but not newman command line. @shamasis You are correct! Thanks for your input.

**Comment by shamasis** [comment]
You're welcone.

**Comment by gaurangpatel79** [comment]
Hi, I also get into the same issue. But its not the cookie. I am passing Authorization header as `bearer {{access_token}}` which is generated in previous request as environment variable. Its all working great in Postman client, but not working with newman in command line. 

below are more details

1. Newman Version (can be found via newman -v): 3.9.2
2. OS details (type, version, and architecture): Ubuntu 16.04.3 LTS
3. Are you using Newman as a library, or via the CLI? via CLI
4. Did you encounter this recently, or has this bug always been there: its same situation like the question here. I just started using it and can not figure out how to do it. I am using it in Postman since long and its working fine with this and lot more environment variables.
5. Command / script used to run Newman:
newman run  https://www.getpostman.com/collections/fa7ade4b1fffc2b085af -e Prod_Environment.postman_environment.json -g globals.postman_globals.json --export-environment Prod_Environment.postman_environment.json --export-globals globals.postman_globals.json

`{
	"variables": [],
	"info": {
		"name": "reachout",
		"_postman_id": "175e4fe8-84e8-e36b-dcee-70f5cc7dbefe",
		"description": "",
		"schema": "https://schema.getpostman.com/json/collection/v2.0.0/collection.json"
	},
	"item": [
		{
			"name": "User Module Test",
			"description": "",
			"item": [
				{
					"name": "Generate Access Token for 9898671735",
					"event": [
						{
							"listen": "test",
							"script": {
								"type": "text/javascript",
								"exec": [
									"var jsonData = JSON.parse(responseBody);",
									"",
									"postman.setEnvironmentVariable(\"access_token\", jsonData.access_token);",
									"postman.setEnvironmentVariable(\"refresh_token\", jsonData.refresh_token);",
									"",
									""
								]
							}
						}
					],
					"request": {
						"url": {
							"raw": "{{localURL}}/reachout/uoauth2/oauth/token",
							"host": [
								"{{localURL}}"
							],
							"path": [
								"reachout",
								"uoauth2",
								"oauth",
								"token"
							],
							"query": [
								{
									"equals": true,
									"key": "scope",
									"value": "read,write",
									"disabled": true
								}
							],
							"variable": []
						},
						"method": "POST",
						"header": [
							{
								"key": "Content-Type",
								"value": "application/json",
								"description": ""
							},
							{
								"key": "Authorization",
								"value": "Basic cmVhY2hvdXQ6cmVhY2hvdXRzZWNyZXQ=",
								"description": ""
							}
						],
						"body": {
							"mode": "raw",
							"raw": "{\n  \"grant_type\":\"password\",\n  \"username\":\"XXXXXXXX\",\n  \"password\":\"XXXXXXX\",\n  \"client_id\":\"XXXXXXXX\",\n  \"client_secret\":\"XXXXXXXX\"\n}"
						},
						"description": "oauth_token"
					},
					"response": []
				},
				{
					"name": "Remove Self 9898671735",
					"event": [
						{
							"listen": "test",
							"script": {
								"type": "text/javascript",
								"exec": [
									"",
									"",
									""
								]
							}
						}
					],
					"request": {
						"url": "{{localURL}}/reachout/users/removeSelf",
						"method": "POST",
						"header": [
							{
								"key": "Content-Type",
								"value": "application/json",
								"description": ""
							},
							{
								"key": "Authorization",
								"value": "bearer {{access_token}}",
								"description": ""
							}
						],
						"body": {
							"mode": "raw",
							"raw": ""
						},
						"description": ""
					},
					"response": []
				}
			]
		}
	]
}`
gives me error
Cannot read property 'toString' of undefined

**Comment by sanjayb1992** [comment]
Hi, 
I want to set environment variable in one request and use it in another request in a single run. Using that --export command didn't help. Can anyone help me out in this?

**Comment by RonakReyhani** [comment]
Hey guys , I went through the issue and didn't get a proper solution , however this ticket had been closed.
this is my Newman response :
in first request it gets the stock id and creates an order for that, when it gets the order, request still using the old value of orderId, while it has to use "01646" . how can I pass this value to my global environment ? instead of using old value? 
the third test is failing as for it can't find old order id!

![image](https://user-images.githubusercontent.com/14250299/56479596-c6158480-64e8-11e9-8a7c-4dd1ed88fd62.png)
