### ISSUE TITLE
Support for another ajax call in pre test and post test . 

### ISSUE THREAD

**Issue by shankyty** [postmanlabs/newman#1143]
Hi all,
I have requirement to fire an api to to clear data in server before test.
And mark end of test on server.
Is there a provision to do that in newman command line.

TIA

**Comment by kunagpal** [comment]
Although AJAX calls are not supported, you can still make requests, like so:
```js
var sdk = require('postman-collection'),
     myreq = new sdk.Request('<ENTER_REQUEST_URL_HERE>');
                                
pm.sendRequest(myreq, function(err, _response) {
        pm.test('request was sent from sandbox', function () {
        pm.expect(_response).to.have.property('code', 200);
        pm.expect(_response).to.have.property('status', 'OK');
    });
});
```

Since the Postman Collection SDK is available inside the Postman Sandbox, you can use the above with Newman v3.7.6 and Postman v5.1.2 or above. For details on creating different kinds of requests, see https://github.com/postmanlabs/postman-collection/blob/develop/test/unit/request.test.js.

**Comment by kunagpal** [comment]
@shankyty Marking this issue as resolved, feel free to revert if you're facing difficulties 😄
