### ISSUE TITLE
Same url is getting returned in the newman report though we see different urls in the newman while executing Postman collection for many iterations(15)

### ISSUE THREAD

**Issue by sravanisatharla** [postmanlabs/newman#1148]
Team,

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
This was encountered recently, Same url is getting returned in the newman report though we see different urls in the newman while executing Postman collection for many iterations(15).
 2. Expected behaviour:
It should take different input data from input sheet and hit different urls

**Comment by kunagpal** [comment]
@sravanisatharla If you're referring to the URLs being grouped in the generated HTML reporter, then this is by design, as the inbuilt HTML reporter aggregates information across multiple iterations (which is the case here, due to your input data sheet). If you wish to view the extended details, please refer https://www.getpostman.com/docs/postman/collection_runs/command_line_integration_with_newman#custom-reporters on how to create your own custom Newman reporter.

**Comment by kunagpal** [comment]
Marking issue as resolved, feel free to get back for any other questions you may have 😄
