### ISSUE TITLE
setNextRequest() not scoped to folder

### ISSUE THREAD

**Issue by mstanielewicz** [postmanlabs/newman#1250]
Hello! 
1. Newman Version (can be found via `newman -v`):    3.8.3
 2. OS details (type, version, and architecture):    macOS High Sierra 10.13
 3. Are you using Newman as a library, or via the CLI?    CLI
 3. Did you encounter this recently, or has this bug always been there:    Just started to use newman
 4. Expected behaviour:    setNextRequest() should be scoped to folder (as Postman documentation says)
 5. Command / script used to run Newman:    newman run {collection.json} -e {env.json} --insecure --delay-request 500
 6. Sample collection, and auxilliary files (minus the sensitive details):    not relevant
 7. Screenshots (if applicable):

![screen shot 2017-10-20 at 15 52 56](https://user-images.githubusercontent.com/7774613/31824259-cb056af4-b5ae-11e7-91c9-0dd4bf9a0845.png)

![screen shot 2017-10-20 at 15 53 40](https://user-images.githubusercontent.com/7774613/31824293-e15bfe58-b5ae-11e7-89db-51adffa5ab60.png)

Steps to reproduce the problem:
1. Create collection with two folders
2. Add two requests with same name to both folders
3. Add setNextRequest() logic in first folder
4. Run collection in newman

**Comment by shamasis** [comment]
setNextRequest will set the next "request" and not folder. :-)

Can we correct the documentation if it says otherwise? @kunagpal @loopDelicious

**Comment by reftel** [comment]
I think you misunderstood the problem. @mstanielewicz' collection, as far as I can see, does not try to switch folder, but is instead assuming that the folder is _not_ changed by the `setNextRequest` call. We have the same issue in our collections. If the request name used in a call to `setNextRequest` is not unique across the whole collection, postman may jump to a request in a different folder.

The documentation on https://www.getpostman.com/docs/v6/postman/collection_runs/building_workflows says:
>  However, if you run a folder, the scope of postman.setNextRequest() is limited to that folder. So you can jump to any request in this folder, but not ones that are outside of the folder.

And that does not match what the implementation does.

**Comment by mstaalesen** [comment]
@shamasis : As @reftel states, we have to use unique names on all requests in a collection to ensure that postman.setNextRequest("name") does not jump to a request in another folder inside the same Collection. 

But I think that the documentation can perhaps just be a bit confusing. Does the following just mean that if you start the runner on "folder level", instead of "collection level"?

> However, if you run a folder, the scope of postman.setNextRequest() is limited to that folder. So you can jump to any request in this folder, but not ones that are outside of the folder.

Basically meaning that if I start the collection runner inside CollectionA/FolderA - It will only jump to requests named "ExampleA" inside "FolderA"? Even though the request "ExampleA" is also a part of FolderB and FolderC? (Hope that made sense)
