### ISSUE TITLE
 Error - socket hang up 

### ISSUE THREAD

**Issue by oabdelsamad** [postmanlabs/newman#1361]
Hi all, 

I was running a test using newman and I got:

` Error: socket hang up ` . Any thoughts?

**Comment by deepakpathania** [comment]
Hey @oabdelsamad, mind sharing little more details about the issue? The fields specified in the issue template would be a good place to start with along with some context. Posting the fields here for your reference. 

 1. Newman Version (can be found via `newman -v`):
 2. OS details (type, version, and architecture):
 3. Are you using Newman as a library, or via the CLI?
 3. Did you encounter this recently, or has this bug always been there:
 4. Expected behaviour:
 5. Command / script used to run Newman:
 6. Sample collection, and auxiliary files (minus the sensitive details):
 7. Screenshots (if applicable):

Steps to reproduce the problem would also help us help you quicker. 
Thanks.

**Comment by oabdelsamad** [comment]
Thank you @deepakpathania - I am updating the issue details as follows:

1. Newman Version: 3.9.1
2. OS details: macOS High Sierra 10.13 (17A365)
3. Are you using Newman as a library, or via the CLI? CLI
4. Did you encounter this recently, or has this bug always been there: I am doing a test where I get all links that are in specific page then I check the response code for them.
5. Expected behaviour: I should not be able to see that error
6. Command / script used to run Newman: newman run xxxxxxx -e xxxxxxxx

![screen shot 2017-12-30 at 6 59 31 pm](https://user-images.githubusercontent.com/21035790/34456014-7eb2bbe8-ed94-11e7-818d-8ea23a7fbaf1.png)

**Comment by deepakpathania** [comment]
Hey, @oabdelsamad Thanks for the detailed description.
Can you please check that the failing request works fine when ran individually and let me know?

**Comment by oabdelsamad** [comment]
@deepakpathania I really appreciate your help. I did run the failing request and it worked fine when ran individually. I also did reboot my machine and run the whole request again and it's no longer failing! Thank you so much, I will mark the issue as closed.
