### ISSUE TITLE
How to stop newman as a node module

### ISSUE THREAD

**Issue by safaorhan** [postmanlabs/newman#1404]
When I started running newman on a collection, how do I interrupt it to cancel the run?

This is the code that runs the collection:
```
newman
    .run({
      collection: runnable.collection,
      iterationData: runnable.iterationData,
      environment: runnable.environment,
      globals: runnable.globals,
      iterationCount: runnable.iterationCount,
    })
    .on('start', () => {
      // on start of run, log to console
      console.log(runnable.name, '\t\t\t', 'Collection run started!');
    })
    .on('beforeItem', (err, args) => {
      if (err) {
        console.error(err);
      } else {
        console.log(runnable.name, '\t\t\t', args.item.name);
      }
    })
    .on('done', (err, summary) => {
      runnable.summary = summary;
      runnable.err = err;
      done();
    });
```

**Comment by kunagpal** [comment]
@safaorhan Could you provide more context on the conditions under which you'd like to abort?

**Comment by safaorhan** [comment]
@kunagpal I am developing a continious integration system. System runs tests when test cases are updated or the tested environment has a new release. Additionally system runs the tests regularly with some interval.

What I'm trying to achieve is when a new `run command` from any trigger has come, cancel old run (don't wait minutes to its completion) and run the new command.

**Comment by kunagpal** [comment]
@safaorhan This is beyond the scope of Newman, as each collection run is meant to be isolated and non-contextually aware of previous/future, or event other simultaneously running collection instances. This is something that will have to be checked as a part of the pre-code run logic. Such logic would have to look for existing runs, and kill them before starting the current run. Alternatively, a simpler way around this problem is to use https://github.com/jenkinsci/throttle-concurrent-builds-plugin.
