### ISSUE TITLE
newman failed to run file upload with collection URL

### ISSUE THREAD

**Issue by xiaweixing** [postmanlabs/newman#1412]
1. Newman Version (can be found via `newman -v`): 3.9.3
 2. OS details (type, version, and architecture): Win10
 3. Are you using Newman as a library, or via the CLI? CLI
 3. Did you encounter this recently, or has this bug always been there: always been there
 4. Expected behaviour: can run file upload successfully with collection URL
 5. Command / script used to run Newman: newman run {collection_url} ...
 6. Sample collection, and auxiliary files (minus the sensitive details):
 7. Screenshots (if applicable):

Steps to reproduce the problem:

1. create a collection with file upload request in postman app (use file c:\TEMP\test.html). it can run successfully in postman app.
![postman_fileupload1](https://user-images.githubusercontent.com/19727572/35900258-0d40be7e-0c25-11e8-89e5-cd12fbfa9f03.png)
2. share the collection in team library, and get the collection guid
3. call getcollection API to fetch the collection, pay attention to the formdata section
![postman_fileupload2](https://user-images.githubusercontent.com/19727572/35900342-97c54fec-0c25-11e8-86c5-04e8f3d5f79f.png)
4. newman run {collection_url}. The file upload request fails.  I logged the request itself, and found formdata is empty
`"method":"POST","body":{"mode":"formdata","formdata":[]}`
5. If I export the collection to a local json, formdata section looks like this:
![postman_fileupload3](https://user-images.githubusercontent.com/19727572/35900530-8b690260-0c26-11e8-9b4a-223203b0d537.png)
6. newman run {collection_json}. The file upload request suceeds.

It seems like newman handles formdata section differently in collection url than in collection json, and leads to execution failure if file upload is run with collection url. But it runs successfully with collection json.

Please help look into this issue, and please let me know if you need more info. Thank you!

**Comment by kunagpal** [comment]
@xiaweixing This is because file paths are not synced as a part of collection data, which is where the Postman API fetches collections and environments from. A workaround is to fetch the collection from the API URL and inject the src values into the paths as needed. This can then be written to a file, and run as usual using Newman. 

I'll keep this issue open while a better fix is worked on. I can't offer an ETA for this at the moment, but this thread will be updated when any progress is made 😄

**Comment by prateeksarda** [comment]
@kunagpal A similar problem I would like to mention for a file upload scenario

I have collection on my machine on Path A eg /data/collection/script.postman_collection.json
It was created on Postman tool and exported as json to my Linux box.

collection.json as downloaded from Postman tool
"body": {
					"mode": "formdata",
					"formdata": [
						{
							"key": "filename",
							"type": "file",
                                                        "src": "source.xml" // its not relative path to file but only file name
						}
					]
		}

I am using a file as source request on same path /data/collection/source.xml (or it could be on different path)
I am running the collection using newman which is running on my machine on lets say root (/) location
newman.run({
  collection : require('/data/collection/script.postman_collection.json')
});

Now even if the source file is in same path as the collection , since newman is running on root path 
it fails to find the file as the newman looks for file in root location.

**Comment by kunagpal** [comment]
@xiaweixing While this is not being worked on at present (since the change in behaviour spans multiple services and systems), a workaround is to fetch the collection from the URL manually and manipulate the collection to include the file paths. This could be done via a simple script that fetches the collection from the Postman API, injects the file paths in the JSON, and runs the collection using Newman.

**Comment by xiaweixing** [comment]
@kunagpal I tried this yesterday and found that the json format for formdata section is same as exported one now, so I guess this issue was fixed somehow, maybe as a side effect by some other fix?  Anyway, it works well with newman now, but it's not working in postman runner, request body is empty, not sure why.

**Comment by esbenbach** [comment]
@xiaweixing  - did you modify the collection locally and it was synced to postman servers or how did you get the src/file path into the collection on the servers?

**Comment by shamasis** [comment]
This issue should be fixed by now since we’ve done a number of tweaks to file handling. Additionally, Postman now exports file path.
