### ISSUE TITLE
Newman error object null on done even though there is an error in a test

### ISSUE THREAD

**Issue by nickyadvokaat** [postmanlabs/newman#1478]
In the code below the `err` object is `null`, even though there is a failing test which is visible in the console output. The code will output 'collection run completed.' When I run the same collection using the CLI I do get an exit(1) error on my console.

```javascript
newman.run({
    collection: require('./sample-collection.json'),
}).on('done', function (err, summary) {
    if (err || summary.error) {
        console.error('collection run encountered an error.');
    }
    else {
        console.log('collection run completed.');
    }
});
```
 1. Newman Version 3.9.3
 2. OS details macOS High Sierra
 3. Are you using Newman as a library, or via the CLI? Library
 3. Did you encounter this recently, or has this bug always been there: Recently
 4. Expected behaviour: I get an `err` object so that I can throw this and get the same behaviour as when using the CLI
 5. Command / script used to run Newman: `node ./script.js` with above script
 6. Sample collection, and auxiliary files (minus the sensitive details):
 7. Screenshots (if applicable):

Steps to reproduce the problem:
Run above script using `node ./script.js` with newman 3.9.3 installed using NPM.

**Comment by kunagpal** [comment]
@nickyadvokaat This is expected behaviour, the `err` argument in the done event handler will only be non-null if the internals of Newman encountered an error whilst trying to run your collection, such as in the case of invalid/missing options. Details on failed tests from your collection run can be derived from `summary.run.failures`, as can be seen here: https://github.com/postmanlabs/newman#newmanruncallbackerror-object--summary-object. If you're using Newman as a CLI tool, you can check for the exit code of the `newman run ...` command, which will help you detect errors/test failures.

**Comment by nickyadvokaat** [comment]
Thank you for clarifying this @kunagpal !
