### ISSUE TITLE
Query: Does Postman/Newman support running Collections/Jsons from another Master Collection/Json? 

### ISSUE THREAD

**Issue by saratrajan** [postmanlabs/newman#1507]
## App Details:

```
Postman for Windows
Version 6.0.10
win32 10.0.16299 / x64
```

## Query:
Is there a way to run Collections from a master level?
e.g: I have module-wise collections for each APIs. I need to be able to run all of them (or some of them) by mentioning the items/order from another Collection (like a Master).

I am not sure if this was a Postman or Newman question. So posting on both the forums.

**Comment by kunagpal** [comment]
@saratrajan Could you provide more context on how these collections are arranged relative to each other? If they're files in a folder, then you can use Newman as has been described here: https://github.com/postmanlabs/newman/blob/develop/examples/run-collections-in-directory.js, in order to run the collections together.

Alternatively, you can effectively trigger collection runs from within a collection by combining the [Monitor trigger API](https://docs.api.getpostman.com/#5b277ca0-7114-e04e-f1f5-246fbbd6d973) with the inbuilt `pm.sendRequest` feature, which is documented here: https://www.getpostman.com/docs/v5/postman/scripts/postman_sandbox_api_reference#pmsendrequest

**Comment by saratrajan** [comment]
Hey @kunagpal - Thanks for the response. I will surely check it out and update this thread.

**Comment by kunagpal** [comment]
@saratrajan Marking this issue as closed, feel free to revert if you're facing issues.
