### ISSUE TITLE
unable to load form file for upload: "[object Object]" - happening when using POSTMAN RUNNER only

### ISSUE THREAD

**Issue by RadhikaPostWoman** [postmanlabs/newman#1627]
I am seeing an issue when running collections via postman RUNNER only which involves uploading files . This is not an issue when running them from standlone postman app. any idea why we are unable to run collections which involves uploading files via RUNNER>?

unable to load form file for upload: "[object Object]"

**Comment by kunagpal** [comment]
@RadhikaPostWoman This is because the file paths are not saved as a part of the collection. A workaround in Newman is to process the collection JSON and inject the paths/variable references yourself, and then run the collection as usual.

Closing as a duplicate of https://github.com/postmanlabs/postman-app-support/issues/812

**Comment by OliverZou** [comment]
closed?why?Any workaround in postman testrunner without newman?

**Comment by shamasis** [comment]
@oliverzou - it’s closed as a duplicate of an issue reported on the correct issue tracker - https://github.com/postmanlabs/postman-app-support/issues/812
