### ISSUE TITLE
The HTML reporter is not installed to the postman/newman_ubuntu1404 Docker container

### ISSUE THREAD

**Issue by mixels** [postmanlabs/newman#1759]
1. Newman Version (can be found via `newman -v`):
    4.1.0 via Docker image postman/newman_ubuntu1404
 2. OS details (type, version, and architecture):
    Docker image postman/newman_ubuntu1404
 3. Are you using Newman as a library, or via the CLI?
    CLI
 3. Did you encounter this recently, or has this bug always been there:
    Recently, but I have not tested old container builds.
 4. Expected behaviour:
    The Docker container should come with the HTML reporter pre-installed.
 5. Command / script used to run Newman:
    newman run {url} -r html --reporter-html-export=/etc/newton
 6. Sample collection, and auxiliary files (minus the sensitive details):
    N/A
 7. Screenshots (if applicable):
    N/A

When running the above command against Newman in the postman/newman_ubuntu1404 Docker container, Newman reports the error:

> newman: "html" reporter could not be loaded.
>  run `npm install newman-reporter-html`

It would be ideal for the Newman Docker container to come with the HTML reporter pre-installed. Sure I can pull the Newman image, modify it, and commit my modifications, but I'd prefer to not have to manage my own images. Is there a reason the HTML reporter isn't included in this Docker image, or could it be added?

Thanks!

**Comment by kunagpal** [comment]
@mixels As can been seen from the Newman changelog here: https://github.com/postmanlabs/newman/blob/develop/CHANGELOG.yaml#L22, the inbuilt HTML reporter was extracted out into its own module to allow faster (independent) iteration and avoid having to make a Newman release for any HTML reporter change.

As for the question of Docker images not including the HTML reporter by default, this was done to ensure that Newman Docker images have the minimum required overhead since Docker images are meant to be as lightweight as possible. That said, documentation on how to use custom reporters with Docker images can be found here: https://github.com/postmanlabs/newman/tree/develop/docker#using-newman-docker-images-with-custom-reporters

**Comment by mixels** [comment]
NPM is reporting that a peer of newman@4 is required but none is installed. From NPM, I don't see a version of the HTML reporter that is compatible with 4.1.0. Is that the case?
