### ISSUE TITLE
certificate "key" and "cert" load error

### ISSUE THREAD

**Issue by bitnahian** [postmanlabs/newman#1803]
1. Newman Version: 4.2.2
2. OS details: Linux <user> 4.14.83-1-MANJARO #1 SMP PREEMPT Fri Nov 23 18:20:11 UTC 2018 x86_64 GNU/Linux
3. Newman as CLI
4. Recently
5. Expected behaviour: Runs without encountering certificate "key" load error and certificate "cert" load error. 
5. Command: 
```sh
newman run v1.json -d Tests/dummyjson.json --ssl-client-cert dsapiTestPrivate.crt --ssl-client-key dsapiTestPrivate.key -e Environments/Braintree\ Payment\ Environment.postman_environment.json
```
6. Shown in command

I've run this collection in the Postman UI, but am failing to run this with newman CLI. 
For every iteration and request, I get:

```
Iteration 1/10

→ BearerToken
  ┌
  │ `certificate "key" load error:  ENOENT: no such file or directory, open 'dsapiTestPrivate.key'`
  │ `certificate "cert" load error:  ENOENT: no such file or directory, open 'dsapiTestPrivate.crt'`
  └
  POST https://url [errored]
     self signed certificate in certificate chain
  2. Check if status code is : OK
  3⠄ JSONError in test-script
```

I've tried absolute and relative file paths as well. Neither of them work. I have my certs in the same directory as the collection json file.

**Comment by alokkdwd** [comment]
Hi @bitnahian , how this issue is resolved, I am also facing same error for certificate when running collection using newman , please suggest 
**error : certificate "cert" load error:  ENOENT: no such file or directory, open 'C:\\Collection\\cert.net4.cert**

Command : newman run postman_collection-new -e Cur01a.postman_environment_1.json -g test.postman_globals.json --ssl-client-key cyberark5.key --ssl-client-cert cert.net4.cert
