### ISSUE TITLE
add ability to build asynchronous reporters

### ISSUE THREAD

**Issue by OmbraDiFenice** [postmanlabs/newman#1933]
Hello everyone,
I would like to build a reporter which will send the report data asynchronously to some service on the network. You can have a look at the reporter I wrote at https://github.com/OmbraDiFenice/newman-reporter-confluence (it's basically a fork of newman-reporter-html with minor changes) to have an idea. See below for a reference to the exact line where I'm trying to do the async request.

The problem is that there is no way to wait for the async request _inside newman_, so that I can be sure that the request is completed before exiting. This is mainly an issue when using newman on the CLI, since the process ends as soon as newman completes, but the async request might still be in progress.
Nonetheless, if there was a way to have newman wait for a promise created inside the reporter, that would fix the issue also when using it as a library.

As far as I understand it is already the way reporters generate output files anyway: a certain object is set so that in newman internals a file can be created with the specified content. Is it possible to put something similar in place for Promises as well?

 1. Newman Version (can be found via `newman -v`): 4.4.0
 2. OS details (type, version, and architecture): Windows 10 x86_64
 3. Are you using Newman as a library, or via the CLI? Both
 3. Did you encounter this recently, or has this bug always been there: N/A (feature request)
 4. Expected behaviour: to be able to send an asynchronous message in reporter before newman exits
 5. Command / script used to run Newman: both `newman run` and as a library
 6. Sample collection, and auxiliary files (minus the sensitive details): see https://github.com/OmbraDiFenice/newman-reporter-confluence/blob/e5746fb239b2ae204111d51951fdb830d4854910/lib/index.js#L300
 7. Screenshots (if applicable):

**Comment by shamasis** [comment]
Just to be sure we are on same page, what do you mean by async request? You mean that you’re making a request from Newman callbacks and you want to wait for the response from that?

If so, I would suggest that you have a common queue for requests that you push from one end when the Newman callback occurs and then clear it from another end as they get populated. I’m saying this because I’m not clear why you cannot use the “done” event to flush all remaining requests and exit. 

Newman having a promise in its calls would cause unexpected side effects and may also influence execution speed (and reliability if your outgoing requests stall/fail.)

Let me know if this approach is something that helps.

**Comment by OmbraDiFenice** [comment]
Well this would be a good solution, but it's not really necessary in my case. The report is generated in the beforeDone event, and I'm already firing the async request in the done event.

I'm not really an expert in node, but as far as I can see there are two different problems:

1. when using newman as a library: the asynchronous request (and therefore the Promise) is generated inside the reporter code, and I could not access it from outside unless:
  a. There is a way to access the newman instance and add a new custom array of promises
  b. There is a way to register some custom event which can be triggered when the promise resolves
  b. I resort to some global variable, which I really don't even want to take into accunt XD

2. when using newman as CLI: since the asynchronous request is independent from the main newman thread, it could happen that node process terminates before the request is completed. This I'm not really sure, I guess it depends on how node handles asynchronous requests

Maybe your solution could help in the first case, even if I'm not really clear how.

For the second scenario, instead, I agree that any problem during a request could cause issues if it stalls. I guess for this case there is nothing to do; the only option would be to add some kind of timeout, but I don't think that it would be a really good solution. 

This means that any reporter that wants to upload data asynchronously can be used only using newman as a library. Am I right?

**Comment by shamasis** [comment]
For point 2, node will wait till all timers (async calls) are fulfilled. 

I would say that you should try creating a new thread on our community forum community.getpostman.com since there maybe people out there who have built similar codebase that they can share. When you post there, I will make sure to bump it up to a few other people I know would love to jump in.

For now, closing this.

**Comment by OmbraDiFenice** [comment]
Hi,
as suggested I created [this post](https://community.getpostman.com/t/asynchronous-upload-of-report-inside-a-newman-reporter/4737) in the forum
