### ISSUE TITLE
Update postman-collection dependency

### ISSUE THREAD

**Issue by romulof** [postmanlabs/newman#1996]
1. Newman Version (can be found via `newman -v`): 4.4.1
 2. OS details (type, version, and architecture): 
 3. Are you using Newman as a library, or via the CLI?
 3. Did you encounter this recently, or has this bug always been there:
 4. Expected behaviour:
 5. Command / script used to run Newman:
 6. Sample collection, and auxiliary files (minus the sensitive details):
 7. Screenshots (if applicable):

Right now there's a stinky fruit in your dependency tree:
`newman@4.4.1` > `postman-collection@3.4.6` > `marked@0.6.1`
https://snyk.io/vuln/SNYK-JS-MARKED-174116

`marked@0.6.2` already has it fixed and `postman-collection@3.4.7` already uses the the fixed version.

The only thing missing is to update your `postman-collection` dependency.

**Comment by shamasis** [comment]
Hey ... thanks for reporting this. We use Snyk here as well!!! That’s a cool coincidence. 

Regarding the update, there are some pending items in that pipeline and since our security team has tested the relatively low impact of the vulnerability, we intend to release dependency bumps with our next release - possibly this month. Having said that if you do find to create an exploitable PoC, please feel free to send at security@getpostman.com and we will revisit this.

**Comment by romulof** [comment]
I believe that `marked` vulnerability should not be exploitable through `newman`.

The reason I'm reporting this is because at my work we have very strict policies for external packages. If Snyk smells something bad, it is blocked. No exceptions.

I'll wait for your next release then. Thanks for the quick reply :)

**Comment by shamasis** [comment]
That’s so understanding of you. The next release of Newman has one cool stuff coming up around dealing with files. So, hope we will make up for the delayed fix on this. 😛

**Comment by yeikel** [comment]
We also have strict rules for dependencies and the vulnerability with **marked** is preventing us from using newman as it was blocked

**Comment by codenirvana** [comment]
@romulof @yeikel We've bumped all the dependencies in Newman v4.5.3.
Please update Newman to the latest and let me know if that fixes this issue.
