### ISSUE TITLE
npm audit fails - lodash

### ISSUE THREAD

**Issue by polson136** [postmanlabs/newman#2060]
![image](https://user-images.githubusercontent.com/2353281/61308506-074ec500-a7b6-11e9-88c7-bbc31a731f34.png)

Npm audit fails due to your usage of lodash. Please either fix it or unpin the version so that we can fix it. There is no reason for it to be pinned, and it's additional maintenance burden for you, since lodash gets security alerts quite regularly.

**Comment by polson136** [comment]
Due to the lack of movement on this issue, I'm just going to uninstall newman...

**Comment by shamasis** [comment]
Hope you know that the issue isn’t exploitable using Newman. If it can be, I would love to have that mailed to security@getpostman.com for further analysis. We ourselves use NPM audit and Snyk to track vulnerabilities and then even try applying those exploits for all standard use cases. 

Additionally, all user scripts run inside Newman is run within a fortified sandbox which further protects usage. If you’re still not comfortable, I cannot force you otherwise. Nevertheless, in our next scheduled release we would update the offending packages as part of general maintenance.

**Comment by polson136** [comment]
I figured that it had probably been looked at. However, there is no reason for a release of newman to be required to get rid of the npm audit warning. The only reason why we are even having this conversation is that newman pins the version of lodash for no good reason. While that may have been recommended before to combat version drift, package-lock.json solves the same problem in a much better way. Lodash is such a widely used package that I would be very surprised if they release breaking changes without a major version bump.

**Comment by shamasis** [comment]
@polson136 ... sure. Will update package soon. We aren’t unpinning versions until we deprecate Node 6. Npm v3 has bugs that don’t respect package lock. 

PS: additionally, you’ll be surprised how much breaking issues even popular package makers can create in minor / patches. 

PS2: I think we’ll actually update this package and release... only for you ❤️❤️ 😊😊

**Comment by codenirvana** [comment]
Fixed in Newman `v4.5.3`.
