### ISSUE TITLE
Misleading usage information

### ISSUE THREAD

**Issue by jamesgeorge007** [postmanlabs/newman#2138]
As of now `newman -h` results in the following:-

```sh
error: no arguments provided

Usage: newman [options] [command]

Options:
  -v, --version               output the version number
  -h, --help                  output usage information

Commands:
  run [options] <collection>  URL or path to a Postman Collection.

To get available options for a command:
  newman [command] -h
```

Usage information should be `newman <command> [options]` instead.

**Comment by codenirvana** [comment]
@jamesgeorge007 Thanks for reporting this issue and suggesting the fix.
But, isn't `newman -v` and `newman -h` are valid commands/arguments which might not necessarily require a `<command>` name.

That's why both options and commands are optional.

However, I noticed that `newman [command] -h` at the end should be `newman <command> -h` as the command is a required argument here.
