### ISSUE TITLE
Newman could not find "cli junit" reporter

### ISSUE THREAD

**Issue by DavidPMacNeil** [postmanlabs/newman#2205]
1. Newman Version (can be found via `newman -v`): 4.5.7 & 4.5.6 (failing on both)
 2. OS details (type, version, and architecture): Windows 10 Pro v.1803 OS Build 17134.765
 3. Are you using Newman as a library, or via the CLI? CLI
 3. Did you encounter this recently, or has this bug always been there: Recently (Started in builds Dec 30th.)
 4. Expected behaviour: Newman to run and publish results via Junit
 5. Command / script used to run Newman: Running through Azure Devops on local machine
Step Install newman
`npm install -g newman`
Step Run newman
`newman run '$(Build.SourcesDirectory)/PostmanTests/Collections/API Integration Tests.postman_collection.json' -e '$(Build.SourcesDirectory)/PostmanTests/Environments/Development.postman_environment.json' --insecure -r cli,junit`
 6. Sample collection, and auxiliary files (minus the sensitive details):
 7. Screenshots (if applicable):

-  The pipeline
![2020-01-07 10_24_09-2020-01-07 10_14_34-Window](https://user-images.githubusercontent.com/5846384/71902306-28c2b500-3138-11ea-879d-bc9bfc3ed30b.png)

- Newman installed on the machine
![2020-01-07 10_15_45-Window](https://user-images.githubusercontent.com/5846384/71901919-55c29800-3137-11ea-94c5-b8c8438017de.png)

- The reporter
![2020-01-07 10_16_39-Window](https://user-images.githubusercontent.com/5846384/71901921-5824f200-3137-11ea-9f56-9b4d31374006.png)

Steps to reproduce the problem:
1. Install newman globally
2. Run newman against a collection with `-r cli,junit`

I have searched through open and closed issues, but only found #1969 which refers to an external reporter. 

This build pipeline has been working for over a year, until it started failing on Dec. 30th, 2019.

**Comment by palprabhat** [comment]
I was having the same issue earlier while trying to use `cli,json`, fixed it by using quotes around it.
`newman run $runnerFileFullName -e $environmentFileFullName --disable-unicode --color off --reporters 'cli,json' --reporter-json-export $reportFile`

**Comment by DavidPMacNeil** [comment]
@palprabhat Huh, yea that did it for me too. Newman needs updated documentation.

**Comment by Wilhop** [comment]
I should add that:
while --reporters 'cli,json' solves the issue while running locally
We use Azure DevOps CI/CD and we have to specify --reporters cli,json without the quotes in azure-pipelines.yml, otherwise it will lead to an error.

So there are use cases for both without quotes and with quotes.

**Comment by 304NotModified** [comment]
> while --reporters 'cli,json' solves the issue while running locally
We use Azure DevOps CI/CD and we have to specify --reporters cli,json without the quotes in azure-pipelines.yml, otherwise it will lead to an error.

It's funny, locally I don't need the quotes, but I need them on Azure Devops. Both are Windows. Tested it with 6.2.1


> @palprabhat Huh, yea that did it for me too. Newman needs updated documentation.

See https://github.com/postmanlabs/newman/pull/3304
