### ISSUE TITLE
v5.0.0 encoding change cause "Unexpected token" w/query parameters.

### ISSUE THREAD

**Issue by sGuid** [postmanlabs/newman#2312]
Last night our automated tests failed with the newman v5.0.0 release (we didn't have newman version pinned.) Works on Newman v4.6.1, and have now pinned to that version.

Error - on a GET with a query parameter, the returned JSON now says "Unexpected token 'F' at 1:1 Failure: 500 Internal Server Error"

**Environment Setup**
 1. Newman Version (can be found via `newman -v`): 5.0.0
 2. OS details (type, version, and architecture): macOS?
 3. Are you using Newman as a library, or via the CLI? node command line via rundeck
 3. Did you encounter this recently, or has this bug always been there: Tests run every hour, started failures at 5pm PST April 8th.
 4. Expected behaviour: encode query parameters correctly, and return correctly.
 5. Command / script used to run Newman: 
...setup stuff
cd /tmp
rm -rf node_modules/newman
[ ! -d "node_modules/newman" ] && npm install -y newman
... clone git, stuff
node node_modules/newman/bin/newman.js run <collection.json> -e <envirnoment.json> --delay-request 100
 6. Sample collection, and auxiliary files (minus the sensitive details): not sure this is needed yet.
 7. Screenshots (if applicable):

**Steps to Reproduce**
Error found when newman runs via rundeck, but reproduces when running newman in terminal. Does not reproduce when running in postman directly with same environment/collection. 

**Expected result** - passes

**Actual result** with v5.0.0
GET https://xxxx?customAttributes={"year":2001} [500 Internal Server Error]

Only the 2 GET requests that include a query in our collection have this issue. The test-script is the same for all our requests.

**Comment by shamasis** [comment]
@sGuid ... sorry to see your test break. Newman v5 has some significant changes under the hood - mostly done to do better encoding and parsing of URLs. We would need to deep dive what exactly failed in this case. 

Would it be possible for you to share your collection (after sanitising any Auth data in it?)

Also, if you’re using the latest Postman App, can you head over to it’s settings (top right wrench icon) and enable “Next Generation URL processing”, send using the app and tell us what error you see in main window and in Postman Console?

cc @codenirvana

**Comment by codenirvana** [comment]
@sGuid as mentioned [here](https://github.com/postmanlabs/postman-app-support/issues/8154), Newman v5 uses the new URL processor which encodes query params as per WHATWG standard.

In your case, the previously encoded `?customAttributes=%7B%22year%22:2001%7D` param will be encoded as `?customAttributes={%22year%22:2001}`.

In most cases, this makes no difference because of the query processor used in the webserver. If you are still facing this issue, you can either:
1. Update your collection and manually encode the `{` and `}` characters to `%7B` and `%7D`
2. or, Add the following pre-request script which will encode the params automatically
```js
pm.request.url.query.each((q) => {
     q.update(encodeURI(q.toString()))
});
```
