### ISSUE TITLE
Bug : Newman CLI Output ( prerequest-scripts & test-scripts )

### ISSUE THREAD

**Issue by Alphasaurs** [postmanlabs/newman#2532]
1. Newman Version (can be found via `newman -v`): 5.2.0
 2. OS details (type, version, and architecture): Windows 10
 3. Are you using Newman as a library, or via the CLI? CLI
 3. Did you encounter this recently, or has this bug always been there: recently
 4. Expected behaviour: 
 5. Command / script used to run Newman:
 6. Sample collection, and auxiliary files (minus the sensitive details):
 7. Screenshots (if applicable):

**Describe the bug**
I ran my json [collection](https://github.com/Alphasaurs/Guardus/tree/master/Postman) and inspected that 
- I have written 0 prerequest-scripts, the newman cli returns  4
- I have written 3 test-scripts but the newman cli returns 6

**To Reproduce**
Run the collection in Newman ClI

**Expected behavior**
-It should return 0 for prerequest-scripts.
-It should return 3 for test-scripts.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/50196057/95048490-8e62c280-0705-11eb-9262-44933d620b2a.PNG)

**Comment by ellachrystelle** [comment]
@Alphasaurs any updates on this? I'm having the same issue

**Comment by adityaofficial10** [comment]
Actually your postman collection consists of 7 empty scripts with 3 of them being test scripts and the rest pre-request scripts.
I think you need to check the way you exported the collection from Postman.
After removing them, the results are correct as shown below:
<img width="848" alt="Screenshot 2021-02-10 at 10 12 04 PM" src="https://user-images.githubusercontent.com/65034276/107541444-265d4500-6bed-11eb-811d-2da43098b6d1.png">

@DannyDainton I don't think if this issue is related to CLI.

**Comment by Alphasaurs** [comment]
@adityaofficial10 thanks for correcting and identifying the problem in this issue, I am closing this issue now.
