### ISSUE TITLE
Deprecate-warning for har-validator@5.1.5

### ISSUE THREAD

**Issue by LindaMohacsi** [postmanlabs/newman#2602]
1. Newman Version (can be found via `newman -v`): 5.2.2
 2. OS details (type, version, and architecture):
 3. Are you using Newman as a library, or via the CLI? cli
 3. Did you encounter this recently, or has this bug always been there: recently
 4. Expected behaviour: no deprecation warning when installing newman 
 5. Command / script used to run Newman:
 6. Sample collection, and auxiliary files (minus the sensitive details):
 7. Screenshots (if applicable):

**Comment by Rey17Alexander** [comment]
8. Screenshot:
![изображение](https://user-images.githubusercontent.com/56083726/108201788-d7666100-7152-11eb-9140-5ad66985b923.png)

**Comment by adityaofficial10** [comment]
@DannyDainton 
Are we open to using a replacement to har-validator here?
If yes, I have a solution ready..

**Comment by DannyDainton** [comment]
I'm not the person to answer those questions 😁

@vvs11 @codenirvana

**Comment by adityaofficial10** [comment]
> I'm not the person to answer those questions 😁
> 
> @vvs11 @codenirvana

I'm sorry for this but you're definitely the person who responds the quickest.😅

**Comment by codenirvana** [comment]
This `npm` warning is expected because the `har-validator` package is no longer maintained and marked as deprecated.
However, this doesn’t affect Newman as the library depending on it is actively maintained and we may drop this dependency in the future.

Refer https://github.com/ahmadnassri/node-har-validator/issues/173 for more details.
