### ISSUE TITLE
Newman to use team shared collections

### ISSUE THREAD

**Issue by TimFowle** [postmanlabs/newman#273]
Is it possible (and if not could it be added) to make newman pull a collection from a team shared collection.
Eg have a group of devs using a shared collection that can then be automatically run in newman using the latest version. This was I can have a jenkins build job that runs a set of tests that have been developed and kept up to date by a group of developers.

Thanks

**Comment by abhijitkane** [comment]
@TimFowle we're working on this, but can't offer an ETA as of now.

**Comment by TimFowle** [comment]
Has this made it to the roadmap yet?  Just curious.
Thanks

**Comment by a85** [comment]
@TimFowle Yep. We are testing it internally. This has a dependency on token management that will be putting out in parallel. Expecting this to be out within the next 2 weeks.

**Comment by TimFowle** [comment]
cool

**Comment by shamasis** [comment]
Ah! Seems like Postman Monitors / Cloud API products. Guessing that this has been resolved so far. Closing. Please reopen if otherwise.

**Comment by TimFowle** [comment]
I still want to be able to run the team collections locally using newman, not externally. Hence still looking for this feature.

**Comment by shamasis** [comment]
But you can do so. Wait - let me do a smal write up and link it here.

Essentially - it would show how to run shared team collections using Newman and CloudAPI.

**Comment by MaxGfeller** [comment]
I just came across this issue because i wanted to do the same. And it is actually really easy with the Cloud API.

- First you need to [generate an API key](https://app.getpostman.com/dashboard/integrations)

**Comment by MaxGfeller** [comment]
I just came across this issue because i wanted to do the same. And it is actually really easy with the Cloud API.

- First you need to [generate an API key](https://app.getpostman.com/dashboard/integrations)
- Get a list of your collections using this link: https://api.getpostman.com/collections?apikey=<yourApiKey>
- Get the link for the specific collection using it's `uid`: https://api.getpostman.com/collections/<collectionUid>?apikey=<apiKey>
- Do the same for your environment using this link: https://api.getpostman.com/environments?apikey=<apiKey>

Now you can run your tests using `newman`: 

```
newman run <collectionUri> --environment <environmentUri>
```
