### ISSUE TITLE
Flag for summary info only

### ISSUE THREAD

**Issue by cameronoxley** [postmanlabs/newman#291]
Hi,

I'm busy building a cron solution for Newman and only want the summary information - is there a way to do this?

**Comment by cameronoxley** [comment]
So I went ahead and included this as an option in my [Newman to Slack](https://github.com/cameronoxley/Newman-to-Slack) library in the meantime.

**Comment by shamasis** [comment]
Hey, this is great. @czardoz @abhijitkane - how about adding this to feature to Newman?

**Comment by shamasis** [comment]
Newman v3 now has ability to show only summary: https://github.com/postmanlabs/newman#cli-reporter-options

```
newman run my-collection.json --reporter-cli-no-failures --reporter-cli-no-assertions --reporter-cli-no-console;
```

**Comment by apurvanataraj88** [comment]
Hey, i know this issue is really old, but I was hoping for some clarification.

My issue currently is that the entire payload is displayed in Slack along with the requests. Because of the size, it splits it into multiple messages, and thus also avoids the `````` symbols to code-ify it. 

![image](https://user-images.githubusercontent.com/45184844/59458367-4ae59600-8de8-11e9-9351-64b4eeca2565.png)

Is there anyway I can avoid those requests and just get the summary? This way it will actually be displayed clean.
I also tried `--reporter-cli-no-failures --reporter-cli-no-assertions --reporter-cli-no-console` along with the `newman` command but was not successful.

Regards

**Comment by NachoColl** [comment]
Still having the issue when using docker and data iterations from csv ...
