### ISSUE TITLE
Find not working properly?

### ISSUE THREAD

**Issue by TimFowle** [postmanlabs/newman#317]
If i perform a search in the results with the latest version of the chrome plugin the search behaves a bit differently to how it used to (from memory):

1. As soon as i type a character it starts to search for that. On long responses this can slow it down greatly as there may be thousands of matches. Im sure it used to wait a little longer so i could type a few characters before it actually searched.

2. If there are multiple results it used to go from one to the next. It now only appears to go to either the first or last entry.

Possibly user error but these appear to be issues.

Thanks

**Comment by czardoz** [comment]
Hi @TimFowle, the issue tracker for the Chrome plugin is here: https://github.com/postmanlabs/postman-app-support/issues

I've created a new issue at https://github.com/postmanlabs/postman-app-support/issues/1677

Since this is not a Newman issue, I am closing this bug, in favor of https://github.com/postmanlabs/postman-app-support/issues/1677, hope that's okay :)
