### ISSUE TITLE
Feature Request- Provide more information in JUnit output file

### ISSUE THREAD

**Issue by cwbell1** [postmanlabs/newman#386]
I think the JUnit testcase file output could be more robust.

1. Append the collection name in full or partial in the test case name record.
1. Provide the request/response details on failed test case records.

**Comment by davenewza** [comment]
If each test could be prefixed with the request name (as an option), it would not only provide more context to each test but also will give each test a unique name (great for build reports!)

**Comment by ebelanger** [comment]
I would really like this feature too and would probably add to ask that the folder name be present too.  The way I organized my tests is that we have one collection which contains one folder for each test case.

It is near impossible right now with this scenario to determine what request failed since they all share similar names because the folder is the discriminator.

**Comment by kunagpal** [comment]
@cwbell1 @ebelanger @davenewza Apologies for the delay, Newman v3.x comes with an improved JUnit reporter, which can be used as follows: `newman run collection.json -r junit,cli --reporter-junit-export report.xml`
