### ISSUE TITLE
Newman 3.0 - Request fails with disabled http request headers in collection

### ISSUE THREAD

**Issue by tojagrut** [postmanlabs/newman#528]
I had some disabled http headers as part of my postman collection.  With upgrade to newman 3.0, seems like they are no longer ignored.  I can remove them as I do not see they are needed at this moment, but not sure if it is intentional change or a bug in 3.0 version.

Fails with error:
_`TypeError       Header name must be a valid HTTP Token ["//Accept"]`_ 

Disabled headers are exported with prefix // in postman collection.

**Comment by shamasis** [comment]
@tojagrut - this bug has been fixed in our runtime. ( @czardoz - right?) and we would bump runtime version in newman real soon.

**Comment by kunagpal** [comment]
@tojagrut: This bug should have been fixed in Newman `v3.0.1`, do get back to us if that is not the case.

**Comment by tojagrut** [comment]
Alright thanks.  I'll have a quick check and let you know.

**Comment by tojagrut** [comment]
It works.

**Comment by softandbyte** [comment]
newman 3.4.3
disabled env var and disabled form-data in post is send .
postman collection can be found here : 
https://www.getpostman.com/collections/6aefac540911714c89c5
env can be found here : (image because i cannot upload json format.)
![image](https://cloud.githubusercontent.com/assets/495673/23162569/fde170c8-f82e-11e6-9bb1-4aa337a47715.png)
