### ISSUE TITLE
3.1.0 breaks support for file fields

### ISSUE THREAD

**Issue by coltonlw** [postmanlabs/newman#570]
Hi, after our builds starting failing without any changes we tracked the issue down to newman failing a request with a file field, message "path must be a string".  We have pinned version 3.0.1 and the issue went away.  It is not the problem with saving "value" property from postman, we manually verified the "value" property of the file field is set correctly in our collection json.

**Comment by kunagpal** [comment]
@coltonlw Please change the key on [this line](https://github.com/scitran/core/blob/master/test/integration_tests/postman/integration_tests.postman_collection#L25) to `"src"` instead of `"value"`, like so:

```json
{
  "key": "file1",
  "src": "test_files/engine-analyses-1.txt",
  "type": "file",
  "enabled": true
}
```

**Comment by coltonlw** [comment]
Can you explain more about what you think is happening?  Was the collection specification changed?

**Comment by shamasis** [comment]
@coltonlw postman did not accurately export file fields. But we could not re use the same field as older apps would start breaking. But in the new format - we use separate fields. Can you try exporting collection in v2 format from the app?

Another note, even if you export in v2 format, since the chrome app variant does not get access to real path (chrome app limitation) the export will never work on chrome apps. It will work on native app variants though.

**Comment by coltonlw** [comment]
After switching to "src" attribute (instead of "value") and collection format v2 this is resolved for us and fixes the issue with postman desktop app clearing the "value" of file fields, since "src" is now what's used by newman.

**Comment by kunagpal** [comment]
@coltonlw Glad to hear that :+1:
