### ISSUE TITLE
The GET request contain the body of the payload

### ISSUE THREAD

**Issue by ajsb85** [postmanlabs/newman#751]
1. Newman Version (can be found via `newman -v`): **v3.2.0**
 2. OS details (type, version, and architecture): **Windows 7**
 3. Are you using Newman as a library, or via the CLI? **CLI**
 3. Did you encounter this recently, or has this bug always been there: **Maybe always**
 4. Expected behaviour: **Status 200 Code Name OK**
 5. Command / script used to run Newman: **newman run file.json**
 6. Sample collection, and auxiliary files (minus the sensitive details): **Any**
 7. Screenshots (if applicable): **No needed**

Steps to reproduce the problem:

1. Add payload body as POST in the Postman Client App
2. Change to GET
3. Save the collection
4. Run newman
5. The GET request contain the body of the raw payload in JSON

**Comment by czardoz** [comment]
This is because the client app currently saves GET request bodies to the collection. 

We are currently in the process of updating our Native apps to properly support bodies in GET requests. When we do that, you will be able to remove bodies from the "Body" tab of Postman. 

For now, one workaround is to change the method from GET to POST in the Postman App, remove the body and save the request.

**Comment by czardoz** [comment]
@kunagpal Just need to add a test and close this up

**Comment by kunagpal** [comment]
@czardoz The appropriate options to enable/disable `GET` request bodies will also have to be added to Newman.

**Comment by kunagpal** [comment]
@ajsb85 Newman `v3.6.0` has been released with a fix for this issue, do go ahead and try it out 😄

**Comment by ajsb85** [comment]
Thank you very much
