### ISSUE TITLE
Set Variable From Command Line

### ISSUE THREAD

**Issue by goldsteindavid** [postmanlabs/newman#764]
I'd like a way to pass a single variable (key:value pair) to Newman from the command line without needing additional JSON files. Currently I'm using -e to set my environment and -d to set initial values for a couple of variables. Each of these switches requires a JSON file. Rather than use -d I'd like to just pass my variable.

I want to be able to do something like this:
`newman run MyAPI.postman_collection.json -e Local.postman_environment.json MyVariable`
Where MyVariable is an environment variable that I would set from the command line (as opposed to from JSON).

**Comment by czardoz** [comment]
@goldsteindavid Newman is designed to be compatible with Postman in all aspects, and there's no proper corresponding feature in Postman.

If you have a secret environment variable, you could probably try creating a temporary environment file for Newman, and then provide that as the argument. If you use the [Postman Cloud API](https://api.getpostman.com/#c34392-1e36-d1cb-af89-1c95365184ab), you can just fetch the environment from a URL instead of a local file :)

**Comment by hwroblewski** [comment]
@czardoz I'm with @goldsteindavid on this one. There is a corresponding feature in Postman, the environment variable. Those aren't only in files, I can set them transiently. Even if there weren't a corresponding feature, there is no reason why newman couldn't have additional functionality.

**Comment by RickvdStaaij** [comment]
Bumping this. I'm building an deployment pipeline including review applications, where every review applications gets his own URL. It would be way nicer to pass an specific environment variable into the CLI instead of having to write it to a file first.

```sh
newman run -v "host:feature-01.yourapp.com" ./test/api_tests.json
```

Don't understand me wrong, the below code works, but it's nasty if you ask me:

```sh
echo '{"values":[{"key":"host","value":"feature-01.yourapp.com"}]}' > ./environment.json
newman run -e ./environment.json ./test/api_tests.json
```

**Comment by kunagpal** [comment]
This is now possible with the `--global-var key=value` option.

**Comment by ek-akqa** [comment]
Would it be possible to override or add an environment variable in the same fashion on the fly?
Say, my environment1 has "foo": "bar1" and my my environment2 has "foo": "bar2"
Now I want to newman run -e environment1.json --env-var foo=bar3

**Comment by mrollo** [comment]
+1

**Comment by iamron** [comment]
+1. Is there a reason for only supporting overrides of globals?

**Comment by kyungmi** [comment]
I solved this problem with `-g` option.

`newman run -g environment.json --global-var "foo=bar"`

**Comment by dkutetsky** [comment]
> This is now possible with the `--global-var key=value` option.

This is not exactly in line with feature request - in our case we are building CI/CD pipeline and have environment json file from developers. So, we need to provide env.json file and override some of the variables by using some "env-var" flag. Also, it could work if newman could recognize data variables from CLI.

Approach with global variables will not work because env variables have higher priority than globals - [variables in Postman](https://www.getpostman.com/docs/v6/postman/environments_and_globals/variables).

Sure, we can read existing env file, parse them, override variables and save, but this is huge workaround that could be illiminated in case newman will have some functionality as Postman.

**Comment by bkosborne** [comment]
Looks like the ability to override env vars was added in PR #1799. Now we just need to wait for the next release 🤞

**Comment by codenirvana** [comment]
@bkosborne  `--env-var` option has been added in Newman v4.4.0.

**Comment by SudoNova** [comment]
Just asking, do you think if it's a good idea to make it even shorter, instead of passing `--env-var foo=bar`, use `--for=bar`, or to avoid conflicts use `--env-foo=bar`? This way Newman usage can be facilitated in terminal hence increases its adoption by admins and  other terminal users.<br>Same thing might be introduced for selecting folders, but it would be more complicated.

**Comment by shamasis** [comment]
Interesting. Sorry if it is a noob question... but how's the current input method preventing "This way Newman usage can be facilitated in terminal hence increases its adoption by admins and other terminal users."?

**Comment by SudoNova** [comment]
@shamasis By saving more characters (hence time) maybe 🤔 As a system or database administrator who has to either use CLIs or calling APIs, especially in critical conditions, this matters a lot. Most avoid using APIs AMAP or do write a huge set of scripts, which are custom and not compatible with OpenAPI (hence not reusable). Newman changes this, but the more convenient it becomes, the more admins embrace it. I prefer `--force` or `--no-force` to `--env-var force=yes/no`.
