### ISSUE TITLE
Tiny Validator Cache is not persistent across postman and newman

### ISSUE THREAD

**Issue by surajrao8** [postmanlabs/newman#809]
**Version and environment information:**
1.  Newman Version:  3.3.0, POSTMAN version(4.9.0), Chrome version (49.0.2623.87)
2.  OS Details : (Ubuntu 16.04, x86 Architecture, 64bit)
3. Are you using Newman as a library, or via the CLI?  : CLI
4.  Did you encounter this recently, or has this bug always been there: Recent Bug
5.  Command / script used to run Newman : newman run test.postman_collection.json

**Steps to reproduce the problem:**
1. Create a Test Collection in POSTMAN named test
2. Add GET operation with Authorization(no Auth), Headers(Empty), Pre-request script as follows:
tv4.dropSchemas();
tv4.addSchema("test", {})

 and Tests as follows:
var arr = tests["Get missing URI's : " +tv4.getSchemaUris()] = true;

3. Export the test collection as Collection v2
4. Using the shell, run the newman command as follows:
newman run test.postman_collection.json

**Expected Result**

2&4. Both the results should be Get missing URI's : test

**Actual Result**
In POSTMAN the result is as desired, in newman the result is Get missing URI's : []

![missingschema_found_in_postman_but_not_in_newman](https://cloud.githubusercontent.com/assets/19496863/21104725/a03d4142-c055-11e6-9e2d-e9f5d5f4ce37.png)

**Comment by czardoz** [comment]
This is by design. For security reasons, Newman and the native Postman apps isolate scripts. This change is coming to the Chrome app as well very soon! 

The correct way of using this is to add the schema in the test script itself. In case you need to pass it from the pre-request script, you should store it in a variable using `postman.setEnvironmentVariable()` and then add it in your test script :-)
