### ISSUE TITLE
Error: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by aarongundel** [postmanlabs/newman#875]
I'm using the Newman 3.4.1 node library on mac OS.  I'm attempting to check an intranet site that uses a certificate signed by our local (corporate) CA.  This works fine through the postman client, but it doesn't work through the library.  I see [Error: self signed certificate in certificate chain] code: 'SELF_SIGNED_CERT_IN_CHAIN' in the summary.  

I know how to get around this issue -- if I use the insecure option.  But I don't really want to do that as I'd like to know if there are issues with the SSL cert.  I tried to use the public key for the root CA, but this doesn't work (Error: error:0906D06C:PEM routines:PEM_read_bio:no start line).  So I'm not sure where to go with this.  I'm not an expert in SSL certs by any means, but I feel like this should work if the cert is trusted on my System (it is).  What am I missing?

**Comment by shamasis** [comment]
Can you answer the following:
1. What Postman App are you using (Chrome extension or native apps) and which version?

2. Is SSL verification turned off in your Postman App settings?

3. What OS are you on?

Ideally, both Postman and Newman should behave the same with self signed server certificates. However chrome app might behave a bit differently since it maintains its own certificate store. Knowing the above could help us answer better. 

Also note that self signed certificate should only work when the insecure flag is turned on or if the signed certificate of the server is part of a chain that is imported properly in your OS. @czardoz could throw more "technical" insights into how to get this to work or why it isn't working.

**Comment by aarongundel** [comment]
I'm using....

Postman for Mac
Version 4.9.3
OS X 16.3.0 / x64

Yeah, it was turned off.  Once I turned it on, it started behaving the same way as the library.  (throwing the SELF-SIGNED error).  

I'm guessing I haven't imported it properly; but I'm not sure where I went wrong, as it's under System and trusted for everything.  Thanks for the response!

**Comment by kunagpal** [comment]
@aarongundel Marking this issue as resolved 😄
