### ISSUE TITLE
Support generation of non-aggregated JUnit reports

### ISSUE THREAD

**Issue by wheleph** [postmanlabs/newman#924]
1. Newman Version (can be found via `newman -v`): 3.4.2
 2. Are you using Newman as a library, or via the CLI? CLI

Historically there are 2 types of JUnit XML reports:
1. "Normal" report ([schema](https://maven.apache.org/surefire/maven-surefire-plugin/xsd/surefire-test-report.xsd)). Example:
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<testsuite tests="1" failures="0" name="com.mycompany.app.AppTest" time="0.002" errors="0" skipped="0">
  <properties>
    <property name="java.runtime.name" value="Java(TM) SE Runtime Environment"/>
    <!-- Lots of other properties... -->
    <property name="sun.cpu.isalist" value=""/>
  </properties>
  <testcase classname="com.mycompany.app.AppTest" name="testApp" time="0.002"/>
</testsuite>
```
2. "Aggregated" report, which looks like this:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Addresses">
  <testsuite name="CreatePrivateCustomerAccountForGetAddress" id="426fbf1a-b1ef-4d51-a68d-9f8b050f91d8" tests="1" time="123">
    <testcase name="Status code is 200"/>
  </testsuite>
  <testsuite name="GetAddressByAddressId" id="dfd4d747-3c56-44db-a9c9-21821d602448" tests="2" time="37">
    <testcase name="Status code is 200"/>
    <testcase name="Address is the right one"/>
  </testsuite>
</testsuites>
```
Newman does support "aggregated" reports but does not support the "normal" ones. This fact causes problems for some tools that consume JUnit reports. Jenkins for example is happy consuming any of the formats but [XL TestView](https://xebialabs.com/products/xl-testview/) can only accept "normal" reports.

So can Newman support "normal" reports?

**Comment by czardoz** [comment]
@wheleph Yes, this is best achieved by writing a [custom reporter](https://github.com/postmanlabs/newman#creating-and-using-custom-reporters). In this case, you can also refer to the [existing JUnit reporter](https://github.com/postmanlabs/newman/blob/dc7344dc1a0aee94c99d762bfa1203cc7aaaf210/lib/reporters/junit/index.js) and tweak it a little to ensure that it doesn't do aggregations. 

I doubt we'll put it in Newman core though, because these cases is exactly what custom reporters should be used for :-) 

I'm closing this issue, but do comment here if you have any trouble creating one.
