### ISSUE TITLE
Can not open The Postman Console

### ISSUE THREAD

**Issue by xiaobeiying** [postmanlabs/newman#962]
I tried command `cmd + alt + c (ctrl + alt + c)` on Mac(10.12.3) and Win 7, and both of Postman version is 4.10.3. 
Like [https://www.getpostman.com/docs/errors](url), the end "For the Native" said, I cannot find `Show Postman Console`.

Do you have this problem and help!!!

**Comment by vegetableman** [comment]
@xiaobeiying Since, you are not able to see the menu `Show Postman Console`. You are probably using the chrome app which doesn't support the `Postman Console` yet. You need to switch to the native app (To download it, you could visit: https://www.getpostman.com/apps). 

Also, please note: app-related issues should be posted on https://github.com/postmanlabs/postman-app-support/issues  ^_^

**Comment by xiaobeiying** [comment]
@vegetableman It seems like that. Thanks a lot. -_- 
Cloesd

**Comment by etune** [comment]
Bummer about the chrome app. I like using Postman on my Chromebook. 

I think Electron apps are bad for the open web.
