### ISSUE TITLE
Cannot run newman right after installation

### ISSUE THREAD

**Issue by fistach** [postmanlabs/newman#995]
When I try to execute a collection of test from the cli like this:

newman run my_collection.json

I get

/usr/bin/env: "node": No such file or directory

 1. Newman Version (can be found via `newman -v`):
newman -v does not work, but newman was installed today with "npm install -g newman".
 2. OS details (type, version, and architecture):
Ubuntu 16.04.2 LTS, x64
 3. Are you using Newman as a library, or via the CLI?
cli
 3. Did you encounter this recently, or has this bug always been there:
It's a first time use.
 4. Expected behaviour:
Application should execute the collection.
 5. Command / script used to run Newman:
newman run my_collection.json
 6. Sample collection, and auxilliary files (minus the sensitive details):
-
 7. Screenshots (if applicable):
-

**Comment by fistach** [comment]
As a workaround it helps if I install

sudo apt-get install nodejs-legacy

**Comment by czardoz** [comment]
@fistach This is because you do not have `node` in your path. I would recommend you install Node using `nvm` on Ubuntu (https://github.com/creationix/nvm), which ensures that the right paths etc are configured, and does not need superuser permissions.

There used to exist a `node` binary, which conflicted with `nodejs`, so they ended up renaming `node` to `nodejs`, which has in turn caused more issues :)

I don't think we'll change Newman to support the `nodejs` binary, because it's non-standard, and specific to Ubuntu. Marking this issue as closed, but let me know if you still have issues getting Newman to work.

**Comment by fistach** [comment]
Ok, thanks for the explanations.
